require.config({
    waitSeconds: 200,
    baseUrl: 'rndr/bower_components',
    paths: {
        //RequireJS plugins
        'async': 'requirejs-plugins/src/async',
        'font': 'requirejs-plugins/src/font',
        'goog': 'requirejs-plugins/src/goog',
        'propertyParser': 'requirejs-plugins/src/propertyParser',
        //3rd party JS libs
        'ace': 'ace-builds/src-min-noconflict/ace',
        'jquery': 'jquery/dist/jquery',
        'jquery-ui': 'jquery-ui/jquery-ui.min',
        'jquery-csv': 'jquery-csv/src/jquery.csv',
        'jquery-ui-touch-punch': 'jqueryui-touch-punch/jquery.ui.touch-punch.min',
        'datatables.net': 'datatables.net/js/jquery.dataTables.min',
        'datatables.net-keytable': 'datatables.net-keytable/js/dataTables.keyTable.min',
        'datatables.net-buttons': 'datatables.net-buttons/js/dataTables.buttons.min',
        'datatables.net-fixedcolumns': 'datatables.net-fixedcolumns/js/dataTables.fixedColumns.min',
        'datatables.net-buttons-print': 'datatables.net-buttons/js/buttons.print.min',
        'datatables.net-buttons-html5': 'datatables.net-buttons/js/buttons.html5.min',
        'downloadjs': 'downloadjs/download.min',
        'cyclejs': '../lib/cycle',
        'pdfmake': 'pdfmake/build/pdfmake.min',
        'vfs_fonts': 'pdfmake/build/vfs_fonts',
        'domReady': 'domready/ready',
        'fastclick': 'fastclick/lib/fastclick',
        'parallax': 'parallax/deploy/jquery.parallax.min',
        'jquery.contextMenu': 'jQuery-contextMenu/src/jquery.contextMenu',
        'gridster': 'gridster/dist/jquery.gridster',
        'ng-rndr-templates': 'rndr/dist/ng-pivot-data-templates.min',
        'ng-rndr': 'rndr/dist/ng-rndr',
        'rndr': 'rndr/dist/rndr',
        'c3': 'c3/c3.min',
        'd3': 'd3/d3.min',
        //Angular and any 3rd party angular modules
        'angular': 'angular/angular.min',
        'angular-material': 'angular-material/angular-material',
        'angular-animate': 'angular-animate/angular-animate',
        'angular-aria': 'angular-aria/angular-aria',
        'angular-resource': 'angular-resource/angular-resource.min',
        'angular-route': 'angular-route/angular-route.min',
        'angular-ui-sortable': 'angular-ui-sortable/sortable',
        'angular-contextMenu': 'angularContextMenu/src/angular-contextMenu',
        'ui-ace': 'angular-ui-ace/ui-ace',
        //rndr plugins
        'c3-renderers': 'rndr/dist/renderers/c3/pivot-data/c3-renderers',
        'd3-renderers': 'rndr/dist/renderers/d3/pivot-data/d3-renderers',
        'datatables-renderers': 'rndr/dist/renderers/datatables/pivot-data/datatables-renderers',
        'pivottables-renderers': 'rndr/dist/renderers/pivottables/pivot-data/pivottables-renderers',
        'pivot-data-ui-renderer': 'rndr/dist/renderers/angular/pivot-data/pivot-data-ui-renderer',
        'gchart-renderers': 'rndr/dist/renderers/google-chart/pivot-data/gchart-renderers',
        'PivotData': 'rndr/dist/data-views/pivot-data/PivotData',
        // '$rndrRenderingEngine': 'rndr/dist/RenderingEngine',
        // '$rndrRenderingEngines': 'rndr/dist/RenderingEngines',
        // '$rndrFormatters': 'rndr/dist/plugins/formatters',
        // '$rndrSorters': 'rndr/dist/plugins/sorters',
        // '$rndrAggregators': 'rndr/dist/plugins/aggregators',
        // '$rndrRenderers': 'rndr/dist/plugins/renderers',
        // '$rndrDataViews': 'rndr/dist/plugins/data-views',
        // '$rndrDerivedAttributes': 'rndr/dist/plugins/derived-attributes',
        // '$rndrAggregatorsTemplates': 'rndr/dist/templates/aggregators',
        // '$rndrDeriverTemplates': 'rndr/dist/templates/derivers.min',
        // '$rndrFormatterTemplates': 'rndr/dist/templates/formatters.min',
        // '$rndrSorterTemplates': 'rndr/dist/templates/sorters.min'
    },
    shim: {
        'font': ['goog', 'propertyParser'],
        'goog': ['async', 'propertyParser'],
        //3rd party JS libs
        'jquery-ui': ['jquery'],
        'jquery-csv': ['jquery'],
        'jquery-ui-touch-punch': ['jquery', 'jquery-ui'],
        'parallax': ['jquery'],
        'gridster': ['jquery'],
        'c3': ['d3'],
        // 'PivotData': ['jquery', '$rndrDataViews', '$rndrSorters', '$rndrAggregators', '$rndrFormatters', '$rndrDerivedAttributes'],
        'gchart-renderers': ['rndr'],
        'c3-renderers': ['rndr', 'jquery', 'c3', 'PivotData'],
        'd3-renderers': ['rndr', 'jquery', 'd3', 'PivotData'],
        'pivottables-renderers': ['rndr', 'jquery', 'PivotData'],
        'pivot-data-ui-renderer': ['ng-rndr', 'angular-material', 'angular-ui-sortable', 'PivotData'],
        'datatables-renderers': ['rndr', 'PivotData', 'jquery', 'datatables.net', 'datatables.net-keytable', 'datatables.net-fixedcolumns', 'datatables.net-buttons-html5', 'datatables.net-buttons-print'],
        'datatables.net': ['jquery'],
        'datatables.net-fixedcolumns': ['datatables.net'],
        'datatables.net-keytable': ['datatables.net'],
        'datatables.net-buttons': ['datatables.net'],
        'datatables.net-buttons-print': ['datatables.net'],
        'datatables.net-buttons-html5': ['datatables.net', 'datatables.net-buttons', 'vfs_fonts'],
        'pdfmake': {
            'exports': 'pdfMake'
        },
        'vfs_fonts': {
            'deps': ['pdfmake'],
            'exports': 'pdfMake'
        },
        'jquery.contextMenu': ['jquery', 'jquery-ui'],
        //Angular and any 3rd party angular modules
        'angular': {
            deps: ['jquery'],
            exports: 'angular'
        },
        'angular-resource': ['angular'],
        'angular-route': ['angular'],
        'angular-material': ['angular', 'angular-animate', 'angular-aria'],
        'angular-animate': ['angular'],
        'angular-aria': ['angular'],
        'angular-ui-sortable': ['angular', 'jquery-ui'],
        'angular-contextMenu': ['angular', 'jquery.contextMenu'],
        'ui-ace': ['angular', 'ace'],
        // '$rndrDataViews': [],
        // '$rndrRenderers': ['$rndrDataViews', '$rndrSorters', '$rndrAggregators'],
        // '$rndrAggregators': ['$rndrAggregatorsTemplates'],
        // '$rndrFormatters': ['$rndrFormatterTemplates'],
        // '$rndrSorters': ['$rndrSorterTemplates'],
        // '$rndrDerivedAttributes': ['$rndrDeriverTemplates'],
        // '$rndrAggregatorsTemplates': ['$rndrFormatters'],
        'rndr': {
            deps: ['jquery']
        },
        'ng-rndr': ['jquery', 'angular', 'rndr', 'ng-rndr-templates'],
        'ng-rndr-templates': ['angular']
    },
    deps: ['../app']
});
