require.config({
    waitSeconds: 200,
    baseUrl: 'examples',
    paths: {
        //RequireJS plugins
        'async': 'bower_components/requirejs-plugins/src/async',
        'font': 'bower_components/requirejs-plugins/src/font',
        'goog': 'bower_components/requirejs-plugins/src/goog',
        'propertyParser': 'bower_components/requirejs-plugins/src/propertyParser',
        //3rd party JS libs
        'ace': 'bower_components/ace-builds/src-min-noconflict/ace',
        'jquery': 'bower_components/jquery/dist/jquery',
        'jquery-ui': 'bower_components/jquery-ui/jquery-ui.min',
        'jquery-csv': 'bower_components/jquery-csv/src/jquery.csv',
        'jquery-ui-touch-punch': 'bower_components/jqueryui-touch-punch/jquery.ui.touch-punch.min',
        'datatables.net': 'bower_components/datatables.net/js/jquery.dataTables.min',
        'datatables.net-keytable': 'bower_components/datatables.net-keytable/js/dataTables.keyTable.min',
        'datatables.net-buttons': 'bower_components/datatables.net-buttons/js/dataTables.buttons.min',
        'datatables.net-fixedcolumns': 'bower_components/datatables.net-fixedcolumns/js/dataTables.fixedColumns.min',
        'datatables.net-buttons-print': 'bower_components/datatables.net-buttons/js/buttons.print.min',
        'datatables.net-buttons-html5': 'bower_components/datatables.net-buttons/js/buttons.html5.min',
        'pdfmake': 'bower_components/pdfmake/build/pdfmake.min',
        'vfs_fonts': 'bower_components/pdfmake/build/vfs_fonts',
        'domReady': 'bower_components/domready/ready',
        'fastclick': 'bower_components/fastclick/lib/fastclick',
        'parallax': 'bower_components/parallax/deploy/jquery.parallax.min',
        'jquery.contextMenu': 'bower_components/jQuery-contextMenu/src/jquery.contextMenu',
        'gridster': 'bower_components/gridster/dist/jquery.gridster',
        'rndr-angular-module': 'bower_components/ngRNDR/dist/rndr',
        'rndr-templates-angular-module': 'bower_components/ngRNDR/dist/rndr-templates',
        'c3': 'bower_components/c3/c3.min',
        'd3': 'bower_components/d3/d3.min',
        //Angular and any 3rd party angular modules
        'angular': 'bower_components/angular/angular.min',
        'angular-material': 'bower_components/angular-material/angular-material',
        'angular-animate': 'bower_components/angular-animate/angular-animate',
        'angular-aria': 'bower_components/angular-aria/angular-aria',
        'angular-resource': 'bower_components/angular-resource/angular-resource.min',
        'angular-route': 'bower_components/angular-route/angular-route.min',
        'angular-ui-sortable': 'bower_components/angular-ui-sortable/sortable',
        'angular-contextMenu': 'bower_components/angularContextMenu/src/angular-contextMenu',
        'ui-ace': 'bower_components/angular-ui-ace/ui-ace'
    },
    shim: {
        'font': ['goog', 'propertyParser'],
        'goog': ['async', 'propertyParser'],
        //3rd party JS libs
        'jquery-ui': ['jquery'],
        'jquery-csv': ['jquery'],
        'jquery-ui-touch-punch': ['jquery', 'jquery-ui'],
        'parallax': ['jquery'],
        'gridster': ['jquery'],
        'c3': ['d3'],
        'src/render/plugins/dist/gchart_renderers.min': ['goog!visualization,1,packages:[charteditor]'],
        'src/render/plugins/dist/c3_renderers.min': ['c3'],
        'src/render/plugins/dist/d3_renderers.min': ['d3'],
        'src/render/plugins/dist/datatables_renderers.min': ['datatables.net', 'datatables.net-keytable', 'datatables.net-fixedcolumns', 'datatables.net-buttons-html5', 'datatables.net-buttons-print'], 
        'datatables.net': ['jquery'],
        'datatables.net-fixedcolumns': ['datatables.net'],
        'datatables.net-keytable': ['datatables.net'],
        'datatables.net-buttons': ['datatables.net'],
        'datatables.net-buttons-print': ['datatables.net'],
        'datatables.net-buttons-html5': ['datatables.net', 'datatables.net-buttons', 'vfs_fonts'],
        'pdfmake': {           
            'exports': 'pdfMake'
        },
        'vfs_fonts': {
            'deps': ['pdfmake'],
            'exports': 'pdfMake'
        },
        'jquery.contextMenu': ['jquery', 'jquery-ui'],
        //Angular and any 3rd party angular modules
        'angular': ['jquery', 'jquery-csv'],
        'angular-resource': ['angular'],
        'angular-route': ['angular'],
        'angular-material': ['angular', 'angular-animate', 'angular-aria'],
        'angular-animate': ['angular'],
        'angular-aria': ['angular'],
        'angular-ui-sortable': ['angular', 'jquery-ui'],
        'angular-contextMenu': ['angular', 'jquery.contextMenu'],
        'rndr-templates-angular-module': ['angular'],
        'ui-ace': ['angular', 'ace'],
        'rndr-angular-module': ['angular', 
                                'angular-route', 
                                'angular-material', 
                                'angular-resource', 
                                'parallax', 
                                'angular-contextMenu', 
                                'datatables.net', 
                                'gridster', 
                                'angular-ui-sortable', 
                                'ui-ace', 
                                'rndr-templates-angular-module']
    },
    deps: ['app']
});